# Generated by Django 3.2.4 on 2021-07-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
